repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
  - repo: local
    hooks: 
    - id: unittest
      name: unittest
      entry: python -m unittest
      language: system
      'types': [python]
      pass_filenames: false
      stages: [commit]
