repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black-jupyter
        language_version: python3.12
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]
  - repo: local
    hooks:
    - id: unittest
      name: unittest
      entry: python -m unittest
      language: system
      'types': [python]
      pass_filenames: false
      stages: [commit]
