# development mode
DEV = true

# download data on init
# if true the data will be downloaded when running the `init` rule, else
# the user will have to run the `load-data` rule to download the data.
LOAD_DATA_ON_INIT = true

# Kaggle
# use the competition name as it appears in the Kaggle URL of the competition
COMPETITION_NAME = 

# Python version
# /!\ PYTHON_VERSION should include the release number (i.e. not 3.x, but 3.x.x)
PYTHON_VERSION = 3.12.1
